name: cube_scanner
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  flutter_ffmpeg: ^0.4.2
  image: ^4.1.3
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  screenshot: ^2.1.0
  cuber: ^0.4.0
  flutter_reactive_ble: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
